x-app-service-template: &ruby-app
  image: ruby-with-nghttp2:0.1
  build:
    dockerfile: Dockerfile
  environment:
    DS9_USE_SYSTEM_LIBRARIES: "1"
    HISTFILE: /app/tmp/.bash_history
    BUNDLE_PATH: /usr/local/bundle
    BUNDLE_CONFIG: /app/.bundle/config
    prometheus_multiproc_dir: ./tmp
  stdin_open: true
  tty: true
  working_dir: /app
  tmpfs:
    - /tmp

services:
  ruby:
    <<: *ruby-app
    command: bash
    volumes:
      - bundler_data:/usr/local/bundle
      - .:/app:cached

  gruf:
    <<: *ruby-app
    command: bundle exec ruby server.rb
    environment:
      SERVER_DIR: ./gruf
    volumes:
      - ./gruf:/app:cached
      - ./shared:/shared:cached
      - bundler_data:/usr/local/bundle

  griffin:
    <<: *ruby-app
    command:  bundle exec ruby server.rb
    volumes:
      - ./griffin:/app:cached
      - ./shared:/shared:cached
      - bundler_data:/usr/local/bundle

  grpc:
    <<: *ruby-app
    command: bundle exec ruby server.rb
    volumes:
      - ./grpc:/app:cached
      - ./shared:/shared:cached
      - bundler_data:/usr/local/bundle

  grpc-multi:
    <<: *ruby-app
    command: bundle exec ruby server_multi.rb
    volumes:
      - ./grpc:/app:cached
      - ./shared:/shared:cached
      - bundler_data:/usr/local/bundle

  falcon:
    <<: *ruby-app
    command: bundle exec falcon host
    volumes:
      - ./falcon:/app:cached
      - ./shared:/shared:cached
      - bundler_data:/usr/local/bundle

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: "1.27.2"
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - gruf

  k6:
    image: grafana/k6
    command: run /app/k6_test_grpc.js
    profiles: [manual-run]
    volumes:
      - .:/app:cached

  grpcurl:
    image: fullstorydev/grpcurl
    profiles: [manual-run]
    volumes:
      - .:/app:cached
    command: >
      -plaintext -proto hello.proto -import-path /app/shared/proto -d '{"name": "Dmitry"}' gruf:9001 hello.Greeter/SayHello

  rust-tonic:
    image: rust-with-protobuf:0.2
    build:
      dockerfile: rust-tonic/Dockerfile
    working_dir: /app/rust-tonic
    environment:
      CARGO_HOME: /usr/cargo
    volumes:
      - .:/app:cached
      - cargo_data:/usr/cargo
    command: >
      cargo run

volumes:
  bundler_data:
  cargo_data:
