x-app-service-template: &app
  image: ruby:3.3
  environment:
    DS9_USE_SYSTEM_LIBRARIES: 1
    HISTFILE: /app/tmp/.bash_history
    BUNDLE_PATH: /usr/local/bundle
    BUNDLE_CONFIG: /app/.bundle/config
    prometheus_multiproc_dir: ./tmp
  working_dir: /app
  volumes:
    - .:/app:cached
    - ${RUBYGEMS_PATH:-..}:/app/vendor/gems:cached
    - bundler_data:/usr/local/bundle
  tmpfs:
    - /tmp

services:
  ruby:
    <<: *app
    command: bash

  gruf:
    <<: *app
    command: bundle exec ruby gruf/server.rb
    ports:
      - "9001:9001"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M

  griffin:
    <<: *app
    command:  bundle exec ruby griffin/server.rb
    #    ports:
    #    #  - "9001:9001"

  k6_gruf:
    image: grafana/k6
    command: run /app/k6_test_grpc.js
    environment:
      TARGET_HOST: "gruf"
    volumes:
      - .:/app:cached

  grpcurl_gruf:
    image: fullstorydev/grpcurl
    volumes:
      - .:/app:cached
    command: >
      -plaintext -proto hello.proto -import-path /app/proto -d '{"name": "Dmitry"}'  gruf:9001 hello.Greeter/SayHello

volumes:
  bundler_data:
