x-app-service-template: &ruby-app
  image: ruby-with-nghttp2:0.1
  build:
    dockerfile: Dockerfile
  environment:
    DS9_USE_SYSTEM_LIBRARIES: "1"
    HISTFILE: /app/tmp/.bash_history
    BUNDLE_PATH: /usr/local/bundle
    BUNDLE_CONFIG: /app/.bundle/config
    prometheus_multiproc_dir: ./tmp
  working_dir: /app
  volumes:
    - .:/app:cached
    - ${RUBYGEMS_PATH:-..}:/app/vendor/gems:cached
    - bundler_data:/usr/local/bundle
  tmpfs:
    - /tmp

services:
  ruby:
    <<: *ruby-app
    command: bash

  gruf:
    <<: *ruby-app
    command: bundle exec ruby gruf/server.rb
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M

  griffin:
    <<: *ruby-app
    command:  bundle exec ruby griffin/server.rb

  k6:
    image: grafana/k6
    command: run /app/k6_test_grpc.js
    volumes:
      - .:/app:cached

  grpcurl:
    image: fullstorydev/grpcurl
    volumes:
      - .:/app:cached
    command: >
      -plaintext -proto hello.proto -import-path /app/proto -d '{"name": "Dmitry"}'  gruf:9001 hello.Greeter/SayHello

  rust-tonic:
    image: rust-with-protobuf:0.2
    build:
      dockerfile: rust-tonic/Dockerfile
    working_dir: /app/rust-tonic
    environment:
      CARGO_HOME: /usr/cargo
    volumes:
      - .:/app:cached
      - cargo_data:/usr/cargo
 
    command: >
      cargo run
 
volumes:
  bundler_data:
  cargo_data:
