# frozen_string_literal: true

source 'https://rubygems.org/'

ruby '~> 3.3'

gem 'grpc',
    github: 'chernenkov-ayu-sbmt/grpc',
    branch: 'feat/DEX-0000/add-jobs-wait-queue',
    submodules: true
