apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    load_module modules/ngx_http_upstream_queue_module.so;
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      upstream gruf {
        server 127.0.0.1:50051 max_conns=32;
        queue 3000 timeout=10;
      }
    
      server {
        listen 0.0.0.0:8080 default_server;
        http2 on;
        
        location / {
          grpc_pass gruf;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gruf-falcon-proxy
  labels:
    app: gruf-falcon-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gruf-falcon-proxy
  template:
    metadata:
      labels:
        app: gruf-falcon-proxy
    spec:
      serviceAccountName: gruf-falcon-proxy-sa
      containers:
        - name: gruf
          image: grpc-proxy/gruf:0.0.1
        - name: nginx
          image: grpc-proxy/nginx:0.0.1
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
        - name: falcon
          image: grpc-proxy/falcon:0.0.1
          ports:
            - containerPort: 8081
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
